# Generated by Django 3.0.7 on 2020-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_mautic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mauticsettings',
            name='mautic_url',
            field=models.URLField(blank=True, help_text='Your Mautic site URL including the https:// prefix - do NOT add a trailing slash', null=True),
        ),
    ]
